gen-block script update to account for new MD format
mukta-strot/marathi-shabd pull request #47
Opened 2021-07-24 16:47 UTC by zarbod

Changed the gen-block script to the new format.

2021-07-24 17:03 UTC, zarbod commented
I had to do a bit of refactoring. I had no idea we moved the code to a new directory. Is there a reason for this?

2021-07-25 00:36 UTC, sanketgarade commented
> I had to do a bit of refactoring. I had no idea we moved the code to a new directory. Is there a reason for this? 


Yes I rearranged the folders to keep all the **browse site** related **code** and the **markdown files** in a single folder. 

Similarly the **search site** front end will be kept in a separate folder in the root path. 

Sorry if I didn't update you on this, but as a general rule make sure you always pull the upstream code before starting to do any changes at your end. Cause I may do some minor changes every now and then on the main repo. 

And thanks for this PR. I'll check it in detail later today.

2021-07-25 09:56 UTC, sanketgarade commented
@zarbod your PR contains the `src` folder in the root path. But all scripts have been moved to `/browse/scripts`. Can you also pls update this PR with the same and test it? Once that is ok, Ill merge it. Make sure that the `src` folder is removed from the root path. (refer the current HEAD on `develop` branch)

2021-07-25 10:11 UTC, sanketgarade requested changes

2021-07-25 10:11 UTC, sanketgarade commented on src/filterdb.py
> +import csv
all files in the src folder to be moved to the browse/scripts folder and the src folder to be removed.

2021-07-26 04:54 UTC, merged

2021-07-26 04:55 UTC, sanketgarade commented on src/filterdb.py
> +import csv
fixed

2021-07-26 04:57 UTC, sanketgarade commented
@zarbod hey I fixed this at my end and tested it. Merged into develop. Thanks a lot!!
I did this on priority since I want to create the markdown files for the browse site.